# config.yml (Admin klasörünün içinde olmalı)

backend:
  name: github
  repo: ekinpkb/site
  branch: main

# Gerekli 1: Media Folder
media_folder: "images" # Medya dosyalarının (resimler) kaydedileceği klasör
public_folder: "/images" # Public URL'si
 
# Gerekli 2: Media Library
media_library: # Bu alan zorunlu, içi boş bile olsa eklenmeli
  name: upload
  
# Gerekli 3: Collections
collections:
  - name: "posts"
    label: "Blog Yazıları"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayınlanma Tarihi", name: "date", widget: "datetime"}
      - {label: "Kategori", name: "category", widget: "string", default: "Genel"}
      - {label: "İçerik", name: "body", widget: "markdown"}